name: Frontend CD

on:
  push:
    branches:
      - main
    paths:
      - "starter/frontend/**"

  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    env:
      REACT_APP_MOVIE_API_URL: http://localhost:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: starter/frontend
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }} \
            --tag frontend:${{ github.sha }} \
            .

      - name: Tag and push Docker image
        run: |
          docker tag frontend:${{ github.sha }} \
            623817460312.dkr.ecr.us-east-1.amazonaws.com/frontend:${{ github.sha }}

          docker push \
            623817460312.dkr.ecr.us-east-1.amazonaws.com/frontend:${{ github.sha }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --name cluster \
            --region us-east-1

      - name: Setup Kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/kustomize

      - name: Deploy Kubernetes manifests
        working-directory: starter/frontend/k8s
        run: |
          kustomize edit set image \
            frontend=623817460312.dkr.ecr.us-east-1.amazonaws.com/frontend:${{ github.sha }}

          kustomize build | kubectl apply -f -